### ISSUE TITLE
Add mini player

### ISSUE THREAD

**Issue by einsteinx2** [einsteinx2/iSub#36]
Should be below the side panel controller and visible at all time. Eventually tapping it will expand the full size player.

Will show current playing song info, show a bar displaying how far in the song the player is, and have a play/pause button.

**Comment by einsteinx2** [comment]
Got the UI stuff done as far as implementing a placeholder mini player view and having it display in the correct place and animate in and out. Now I just need to implement the mini player view itself, should have it checked in tonight or tomorrow.

**Comment by luckydonald** [comment]
Impressive 👍
