### ISSUE TITLE
Album art not displaying on lock screen for song that has art

### ISSUE THREAD

**Issue by einsteinx2** [einsteinx2/iSub#48]

**Comment by aaronk6** [comment]
Same here (build 209).

<img src="https://cloud.githubusercontent.com/assets/446063/22403601/12265432-e61d-11e6-871e-4f16902ba176.PNG" width="160">
<img src="https://cloud.githubusercontent.com/assets/446063/22403600/1223d108-e61d-11e6-9d09-e16875505eb8.PNG" width="160">
