### ISSUE TITLE
App sometimes crashing when tapping on “Play all”

### ISSUE THREAD

**Issue by aaronk6** [einsteinx2/iSub#61]
Currently, this seems random to me. Will add more information as soon as I recognize a pattern.

**Update:** This also seems to happen when the app is in background and an album is being played. The playback sometimes just stops after a track (never during a track). When I then reopen the app, I notice that it has probably crashed because I’m back in the Folders view and the AirPlay connection is lost.

(build 209)

**Comment by einsteinx2** [comment]
I'll look through the crashes in hockeyapp and get them fixed for the next build.

**Comment by einsteinx2** [comment]
Background issues should be resolved now.
