### ISSUE TITLE
No option to enable AirPlay or a Bluetooth audio from within the app

### ISSUE THREAD

**Issue by aaronk6** [einsteinx2/iSub#62]
Works fine when selecting AirPlay from iOS Control Center.

I assume that this is just missing from the UI and will be added eventually.

(build 209)

**Comment by einsteinx2** [comment]
Created issues for these. Chromecase will have to come after the iSub 4 release as I have a block on new features to make sure it finally gets released :)

Add output selector to Player UI for airplay/bluetooth #106
Add Chromcast support #107
