### ISSUE TITLE
Create loader for Subsonic createPlaylist.view API call

### ISSUE THREAD

**Issue by einsteinx2** [einsteinx2/iSub#79]

**Comment by Rolvar** [comment]
needs an explanation of persist function, esentially I put the same of PlaylistLoader.swift, cuz the API response is the new playlist created so, I have to manage as if I we called the playlist, but I don't know how that "persist" function works and what it is for, then maybe today we can talk about this, to continue with the updatePlaylist wich also is very similar to createPlaylist.
