### ISSUE TITLE
Track bookmarks

### ISSUE THREAD

**Issue by p-ang** [einsteinx2/iSub#8]
It is currently not possible to add bookmarks with the same name on different songs - if I do, the newer bookmark would overwrite the previous. Is it possible to add this functionality? 

(it would also be great if it was possible to export the list of bookmarks - ie. to an email message)

**Comment by einsteinx2** [comment]
Thanks for pointing this out. I reviewed the bookmark saving logic and to be honest, I'm not sure why I originally added that check for duplicate named bookmarks. You should be able to make as many bookmarks with any name you want, as they include timestamp and song info to tell them apart. 

I've removed that check, and the fix will be in the next bug fix update. Currently waiting on my account switching from business to individual, so I can't submit any updates. But after that is complete, I'll post one.
