### ISSUE TITLE
Check iOS9 support... is it there?

### ISSUE THREAD

**Issue by mlabbe** [einsteinx2/iSub#9]
Really, this is me just asking if iOS9 is compatible with iSub.  I still use iSub all day every day, and I would seriously consider not upgrading to iOS9 if it didn't broke iSub.  I know it's been in public beta for awhile and I hope someone took the plunge.

**Comment by garethmccall** [comment]
Current AppStore build works for me.

**Comment by einsteinx2** [comment]
I've been living on iOS 9 since beta 1 and haven't noticed any issues with iSub. Looks like the API transition is much smoother this time than from 7 to 8. I don't have any compatibility update planned, though I am working on a small bug fix update unrelated to the transition.

**Comment by mlabbe** [comment]
Thanks!!
